# Generated by Django 2.2 on 2021-03-30 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210324_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата публикации поста', verbose_name='Дата'),
        ),
    ]
