# Generated by Django 3.1.7 on 2021-04-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210405_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Укажите ключ для страницы группы, используйте только латиницу, цифры, дефисы и подчёркивания.', max_length=100, unique=True, verbose_name='Ключ ссылки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Укажите группу, если такая есть', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Расскажите о чём ваш пост', verbose_name='Текст'),
        ),
    ]
